apiVersion: apps/v1
kind: Deployment
metadata:
  name: langserve-base
  namespace: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langserve-base
  template:
    metadata:
      labels:
        app: langserve-base
    spec:
      containers:
        - name: langserve-base
          image: langserve-base
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "langserve-base"
            - name: APP_HOST
              value: "0.0.0.0"
            - name: APP_PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: langserve-base
  namespace: ai-service
spec:
  selector:
    app: langserve-base
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
